// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy3_eBS_3sUPkWr3bY4CxyXCiItXT08wI',
    appId: '1:83338009381:web:34593008febdff159e58cc',
    messagingSenderId: '83338009381',
    projectId: 'programming-mobile',
    authDomain: 'programming-mobile.firebaseapp.com',
    databaseURL: 'https://programming-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programming-mobile.firebasestorage.app',
    measurementId: 'G-6F42VLP00K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpuvnAPinWROAFgqA83gB52-GQRAjSG6Y',
    appId: '1:83338009381:android:200a8392a50c70319e58cc',
    messagingSenderId: '83338009381',
    projectId: 'programming-mobile',
    databaseURL: 'https://programming-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programming-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH-irlYRajmomk9IHwToLH8ZCa_gXh6Co',
    appId: '1:83338009381:ios:5f0cdea3414dc9159e58cc',
    messagingSenderId: '83338009381',
    projectId: 'programming-mobile',
    databaseURL: 'https://programming-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programming-mobile.firebasestorage.app',
    iosBundleId: 'com.ush.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH-irlYRajmomk9IHwToLH8ZCa_gXh6Co',
    appId: '1:83338009381:ios:417e6c3c1f1b1d2c9e58cc',
    messagingSenderId: '83338009381',
    projectId: 'programming-mobile',
    databaseURL: 'https://programming-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programming-mobile.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy3_eBS_3sUPkWr3bY4CxyXCiItXT08wI',
    appId: '1:83338009381:web:beb82923017a22959e58cc',
    messagingSenderId: '83338009381',
    projectId: 'programming-mobile',
    authDomain: 'programming-mobile.firebaseapp.com',
    databaseURL: 'https://programming-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'programming-mobile.firebasestorage.app',
    measurementId: 'G-81ZX74CVFJ',
  );
}
